# Code generated by go.einride.tech/sage. DO NOT EDIT.
# To learn more, see .sage/main.go and https://github.com/einride/sage.

.DEFAULT_GOAL := all

cwd := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
sagefile := $(abspath $(cwd)/.sage/bin/sagefile)

# Setup Go.
go := $(shell command -v go 2>/dev/null)
export GOWORK ?= off
ifndef go
SAGE_GO_VERSION ?= 1.25.5
export GOROOT := $(abspath $(cwd)/.sage/tools/go/$(SAGE_GO_VERSION)/go)
export PATH := $(PATH):$(GOROOT)/bin
go := $(GOROOT)/bin/go
os := $(shell uname | tr '[:upper:]' '[:lower:]')
arch := $(shell uname -m)
ifeq ($(arch),x86_64)
arch := amd64
endif
$(go):
	$(info installing Go $(SAGE_GO_VERSION)...)
	@mkdir -p $(dir $(GOROOT))
	@curl -sSL https://go.dev/dl/go$(SAGE_GO_VERSION).$(os)-$(arch).tar.gz | tar xz -C $(dir $(GOROOT))
	@touch $(GOROOT)/go.mod
	@chmod +x $(go)
endif

.PHONY: $(sagefile)
$(sagefile): $(go)
	@cd .sage && $(go) mod tidy && $(go) run .

.PHONY: sage
sage:
	@$(MAKE) $(sagefile)

.PHONY: update-sage
update-sage: $(go)
	@cd .sage && $(go) get go.einride.tech/sage@latest && $(go) mod tidy && $(go) run .

.PHONY: clean-sage
clean-sage:
	@git clean -fdx .sage/tools .sage/bin .sage/build

.PHONY: all
all: $(sagefile)
	@$(sagefile) All

.PHONY: generate-gha
generate-gha: $(sagefile)
	@$(sagefile) GenerateGHA

.PHONY: git-diff-check
git-diff-check: $(sagefile)
	@$(sagefile) GitDiffCheck

.PHONY: go-build
go-build: $(sagefile)
	@$(sagefile) GoBuild

.PHONY: go-format
go-format: $(sagefile)
	@$(sagefile) GoFormat

.PHONY: go-lint
go-lint: $(sagefile)
	@$(sagefile) GoLint

.PHONY: go-mod-tidy
go-mod-tidy: $(sagefile)
	@$(sagefile) GoModTidy

.PHONY: go-test
go-test: $(sagefile)
	@$(sagefile) GoTest

.PHONY: go-vulncheck
go-vulncheck: $(sagefile)
	@$(sagefile) GoVulncheck

.PHONY: lua-format
lua-format: $(sagefile)
	@$(sagefile) LuaFormat

.PHONY: python-format
python-format: $(sagefile)
	@$(sagefile) PythonFormat

.PHONY: python-lint
python-lint: $(sagefile)
	@$(sagefile) PythonLint

.PHONY: python-mypy
python-mypy: $(sagefile)
	@$(sagefile) PythonMypy

.PHONY: python-sync
python-sync: $(sagefile)
	@$(sagefile) PythonSync

.PHONY: python-test
python-test: $(sagefile)
	@$(sagefile) PythonTest

.PHONY: run-synced
run-synced: $(sagefile)
	@$(sagefile) RunSynced

.PHONY: run-synced-serial
run-synced-serial: $(sagefile)
	@$(sagefile) RunSyncedSerial

.PHONY: sync
sync: $(sagefile)
	@$(sagefile) Sync
