package targets

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"

	"github.com/fredrikaverpil/sage-ci/config"
)

// TargetInfo describes a generated target function.
type TargetInfo struct {
	Name       string // e.g., "GoLint"
	FuncName   string // e.g., "goLint"
	Ecosystem  string // e.g., "Go", "Python", "Lua"
	ModulesVar string // e.g., "GoModules", "PythonModules", "LuaModules"
}

// allTargets defines all available targets grouped by ecosystem.
var allTargets = []TargetInfo{
	// Go targets.
	{Name: "GoModTidy", FuncName: "goModTidy", Ecosystem: "Go", ModulesVar: "GoModules"},
	{Name: "GoFormat", FuncName: "goFormat", Ecosystem: "Go", ModulesVar: "GoModules"},
	{Name: "GoLint", FuncName: "goLint", Ecosystem: "Go", ModulesVar: "GoModules"},
	{Name: "GoTest", FuncName: "goTest", Ecosystem: "Go", ModulesVar: "GoModules"},
	{Name: "GoVulncheck", FuncName: "goVulncheck", Ecosystem: "Go", ModulesVar: "GoModules"},
	// Python targets.
	{Name: "PythonSync", FuncName: "pythonSync", Ecosystem: "Python", ModulesVar: "PythonModules"},
	{Name: "PythonFormat", FuncName: "pythonFormat", Ecosystem: "Python", ModulesVar: "PythonModules"},
	{Name: "PythonLint", FuncName: "pythonLint", Ecosystem: "Python", ModulesVar: "PythonModules"},
	{Name: "PythonMypy", FuncName: "pythonMypy", Ecosystem: "Python", ModulesVar: "PythonModules"},
	{Name: "PythonTest", FuncName: "pythonTest", Ecosystem: "Python", ModulesVar: "PythonModules"},
	// Lua targets.
	{Name: "LuaFormat", FuncName: "luaFormat", Ecosystem: "Lua", ModulesVar: "LuaModules"},
}

// targetsTemplate is the template for generating targets.gen.go.
const targetsTemplate = `// Code generated by sage-ci. DO NOT EDIT.

package main

import (
	"context"

	"github.com/fredrikaverpil/sage-ci/targets"
)

{{range .Targets}}
// {{.Name}} runs the {{.FuncName}} target for configured {{.Ecosystem}} modules.
func {{.Name}}(ctx context.Context) error {
	return targets.{{.Name}}(ctx, cfg)
}
{{end}}
// GenerateWorkflows regenerates CI workflows for the configured platform.
func GenerateWorkflows(ctx context.Context) error {
	return targets.GenerateWorkflows(cfg)
}

// UpdateSageCi updates the sage-ci dependency and regenerates Makefiles and workflows.
func UpdateSageCi(ctx context.Context) error {
	return targets.UpdateSageCi(ctx, cfg)
}
`

// GenerateTargetsFile generates a targets.gen.go file in the specified directory.
// It only includes targets for ecosystems that have modules configured.
func GenerateTargetsFile(cfg config.Config, outputDir string) error {
	// Filter targets based on configured ecosystems.
	var enabledTargets []TargetInfo
	for _, t := range allTargets {
		switch t.ModulesVar {
		case "GoModules":
			if len(cfg.GoModules) > 0 {
				enabledTargets = append(enabledTargets, t)
			}
		case "PythonModules":
			if len(cfg.PythonModules) > 0 {
				enabledTargets = append(enabledTargets, t)
			}
		case "LuaModules":
			if len(cfg.LuaModules) > 0 {
				enabledTargets = append(enabledTargets, t)
			}
		}
	}

	if len(enabledTargets) == 0 {
		// No targets to generate; remove the file if it exists.
		outputPath := filepath.Join(outputDir, "targets.gen.go")
		if err := os.Remove(outputPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove targets.gen.go: %w", err)
		}
		return nil
	}

	// Parse and execute template.
	tmpl, err := template.New("targets").Parse(targetsTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	data := struct {
		Targets []TargetInfo
	}{
		Targets: enabledTargets,
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	// Format the generated code.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated code: %w", err)
	}

	// Write to file.
	outputPath := filepath.Join(outputDir, "targets.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write targets.gen.go: %w", err)
	}

	return nil
}
